annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update outlinewiki/outline image version to 1.1.0
      links:
        - name: Upstream Project
          url: https://hub.docker.com/r/outlinewiki/outline
    - kind: changed
      description: Update dependency redis from 23.2.2 to 23.2.12
      links:
        - name: ArtifactHub
          url: https://artifacthub.io/packages/helm/bitnami/redis
    - kind: changed
      description: Update dependency postgresql from 18.1.3 to 18.1.9
      links:
        - name: ArtifactHub
          url: https://artifacthub.io/packages/helm/bitnami/postgresql
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: outline
      image: outlinewiki/outline:1.1.0
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Chart Usage Page
      url: https://community-charts.github.io/docs/charts/outline/usage
    - name: Upstream Project
      url: https://github.com/outline/outline/
    - name: Official Usage Documentation
      url: https://docs.getoutline.com/s/guide
    - name: Official Hosting Documentation
      url: https://docs.getoutline.com/s/hosting/
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Outline Home Page
      url: https://user-images.githubusercontent.com/380914/110356468-26374600-7fef-11eb-9f6a-f2cc2c8c6590.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc
apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 23.2.12
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 18.1.9
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.4.0
description: A Helm chart for the fastest knowledge base for growing teams. Beautiful,
  realtime collaborative, feature packed, and markdown compatible.
home: https://www.getoutline.com/
icon: https://avatars.githubusercontent.com/u/1765001?s=200&v=4
keywords:
- outline
- knowledge base
- knowledge
- docs
- documentation
- collaboration
- markdown
- wiki
kubeVersion: '>=1.23.0-0'
maintainers:
- email: burak.ince@linux.org.tr
  name: burakince
  url: https://www.burakince.com
name: outline
sources:
- https://github.com/community-charts/helm-charts
- https://github.com/outline/outline/
type: application
version: 0.7.3
