---
apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
  namespace: outline
type: Opaque
stringData:
  # Outline secrets
  SECRET_KEY: "4d73b711454c47b8365346dead3da86d4f0f3a2537ebda531f3f0dfec310334c"
  UTILS_SECRET: "0bead7b5841be2cd9d31a34d1921beb1ded5eede61ac8f9fb52f1087075c6898"

  # Postgres credentials
  POSTGRES_USER: "outline"
  POSTGRES_PASSWORD: "Passw0rd123"
  POSTGRES_DB: "outline"

  # Connection strings (use Kubernetes service DNS names)
  DATABASE_URL: "postgres://outline:Passw0rd123@outline-postgres:5432/outline"
  REDIS_URL: "redis://outline-redis:6379"
